import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { KeyRound, MailCheck } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

export default function AccountHelp() {
  const [, setLocation] = useLocation(); const [mode, setMode] = useState<"verify" | "reset">("verify"); const [email, setEmail] = useState("");
  const verify = trpc.proctorx.credentials.requestVerification.useMutation(); const reset = trpc.proctorx.credentials.requestPasswordReset.useMutation(); const action = mode === "verify" ? verify : reset; const result = action.data?.delivery;
  const request = () => mode === "verify" ? verify.mutate({ email, origin: window.location.origin }) : reset.mutate({ email, origin: window.location.origin });
  return <div className="grid-backdrop grid min-h-screen place-items-center bg-[#05060b] p-5"><main className="hud-panel w-full max-w-md p-7 sm:p-9"><button onClick={() => setLocation("/")} className="font-display font-bold">PROCTOR<span className="text-pink-400">X</span></button><p className="mt-8 tech-label">Account recovery</p><h1 className="mt-2 font-display text-3xl font-bold">Verification &amp; password help</h1><div className="mt-6 grid grid-cols-2 border border-cyan-200/15 p-1"><button onClick={() => setMode("verify")} className={`py-2 text-xs ${mode === "verify" ? "bg-cyan-300 text-slate-950" : "text-muted-foreground"}`}>Verify email</button><button onClick={() => setMode("reset")} className={`py-2 text-xs ${mode === "reset" ? "bg-pink-400 text-slate-950" : "text-muted-foreground"}`}>Reset password</button></div>{result ? <div className="mt-6 text-center"><MailCheck className="mx-auto h-10 w-10 text-cyan-300" /><p className="mt-4 text-sm leading-6 text-muted-foreground">{result.mode === "configuration_required" ? "If verification is still needed, sign in again with your email and password to request a fresh secure verification email." : "If this account exists, a secure email has been sent. Firebase-hosted links expire automatically and can be used only once."}</p>{result.mode === "preview" && result.previewUrl ? <a href={result.previewUrl} className="mt-5 inline-flex w-full justify-center bg-cyan-300 px-4 py-3 text-sm font-semibold text-slate-950">Open development link</a> : null}</div> : <div className="mt-6 space-y-3"><Input value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="Student email" className="border-cyan-200/30 bg-black/25 placeholder:text-slate-400" /><Button disabled={!email || action.isPending} onClick={request} className="w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{mode === "verify" ? <MailCheck className="mr-1 h-4 w-4" /> : <KeyRound className="mr-1 h-4 w-4" />}{action.isPending ? "Sending…" : mode === "verify" ? "Send verification email" : "Send reset email"}</Button></div>}<p className="mt-6 text-center text-sm text-muted-foreground"><Link href="/signin" className="text-pink-300">Back to sign in</Link></p></main></div>;
}
