import { Button } from "@/components/ui/button";
import { SupportChat } from "@/components/SupportChat";
import { useProctoring } from "@/hooks/useProctoring";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Camera, Check, ChevronLeft, ChevronRight, Clock3, Expand, Flag, ScanFace, Send, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";
import { getRemainingExamSeconds } from "../../../shared/examTiming";

function asTime(seconds: number) { const value = Math.max(0, seconds); return `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`; }

function DeviceReadiness({ cameraStatus }: { cameraStatus: "idle" | "requesting" | "monitoring" | "blocked" | "unavailable" }) {
  const [visible, setVisible] = useState(true);
  const [fullscreenEnabled, setFullscreenEnabled] = useState(false);
  const [secureContext, setSecureContext] = useState(true);
  useEffect(() => {
    const refresh = () => { setVisible(!document.hidden); setFullscreenEnabled(document.fullscreenEnabled); setSecureContext(window.isSecureContext); };
    refresh(); document.addEventListener("visibilitychange", refresh); return () => document.removeEventListener("visibilitychange", refresh);
  }, []);
  const checks = [
    { label: "Secure browser context", ready: secureContext },
    { label: "Fullscreen available", ready: fullscreenEnabled },
    { label: "Window in foreground", ready: visible },
    { label: "Camera signal", ready: cameraStatus === "monitoring" },
  ];
  return <div className="mt-4 border-t border-cyan-200/10 pt-4"><p className="tech-label text-[0.52rem]">Readiness status</p><div className="mt-2 grid gap-1.5">{checks.map(check => <div key={check.label} className="flex items-center justify-between text-[0.68rem]"><span className="text-muted-foreground">{check.label}</span><span className={check.ready ? "text-cyan-200" : "text-pink-200"}>{check.ready ? "Ready" : "Needs attention"}</span></div>)}</div><p className="mt-3 text-[0.62rem] leading-4 text-muted-foreground">Keep this tab visible and remain in fullscreen while the assessment is active. Returning from the background or leaving fullscreen may be logged.</p></div>;
}

export default function ExamConsole() {
  const [, params] = useRoute("/exam/:attemptId"); const attemptId = Number(params?.attemptId); const [, setLocation] = useLocation();
  const attemptQuery = trpc.proctorx.student.getAttempt.useQuery({ attemptId }, { enabled: Number.isInteger(attemptId) && attemptId > 0, refetchInterval: 15000 });
  const saveAnswer = trpc.proctorx.student.saveAnswer.useMutation();
  const submit = trpc.proctorx.student.submitAttempt.useMutation({ onSuccess: () => setLocation(`/result/${attemptId}`), onError: error => toast.error(error.message) });
  const logEvent = trpc.proctorx.proctoring.logEvent.useMutation();
  const [currentIndex, setCurrentIndex] = useState(0); const [answers, setAnswers] = useState<Record<number, string | null>>({}); const [review, setReview] = useState<Record<number, boolean>>({}); const [warning, setWarning] = useState<string | null>(null); const [remainingSeconds, setRemainingSeconds] = useState<number | null>(null);
  const data = attemptQuery.data; const exam = data?.attempt;
  const emitSignal = useCallback((eventType: "camera_interrupted" | "face_absent" | "multiple_faces" | "fullscreen_exit" | "tab_hidden" | "device_check_failed", durationMs: number) => { if (!attemptId) return; logEvent.mutate({ attemptId, eventType, durationMs }, { onSuccess: result => { if (result.shouldWarn) setWarning(result.submitted ? "Integrity threshold reached. The attempt was submitted for review." : "Integrity signal detected. Please correct your environment and continue."); if (result.submitted) setLocation(`/result/${attemptId}`); } }); }, [attemptId, logEvent, setLocation]);
  const config = useMemo(() => ({ faceAbsentThresholdSeconds: Number((exam?.proctoringConfig as Record<string, unknown> | null)?.faceAbsentThresholdSeconds ?? 3), multipleFaceThresholdSeconds: Number((exam?.proctoringConfig as Record<string, unknown> | null)?.multipleFaceThresholdSeconds ?? 3) }), [exam?.proctoringConfig]);
  const proctoring = useProctoring({ ...config, onSignal: emitSignal });
  useEffect(() => { if (!exam?.startedAt || !exam?.durationSeconds || exam.status !== "in_progress") return; const tick = () => { const seconds = getRemainingExamSeconds(Date.now(), new Date(exam.startedAt), exam.durationSeconds, exam.endsAt ? new Date(exam.endsAt) : null); setRemainingSeconds(seconds); if (seconds <= 0 && !submit.isPending) submit.mutate({ attemptId, reason: "timeout" }); }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [attemptId, exam?.durationSeconds, exam?.endsAt, exam?.startedAt, exam?.status, submit]);
  useEffect(() => { const onVisibility = () => { if (document.hidden) emitSignal("tab_hidden", 0); }; const onFullscreen = () => { if (proctoring.status === "monitoring" && !document.fullscreenElement) emitSignal("fullscreen_exit", 0); }; document.addEventListener("visibilitychange", onVisibility); document.addEventListener("fullscreenchange", onFullscreen); return () => { document.removeEventListener("visibilitychange", onVisibility); document.removeEventListener("fullscreenchange", onFullscreen); }; }, [emitSignal, proctoring.status]);
  useEffect(() => () => proctoring.stop(), [proctoring.stop]);
  useEffect(() => {
    if (exam?.status && exam.status !== "in_progress") setLocation(`/result/${attemptId}`);
  }, [attemptId, exam?.status, setLocation]);
  if (attemptQuery.isLoading) return <div className="grid min-h-screen place-items-center tech-label">Loading protected exam session…</div>;
  if (!data || !exam) return <div className="grid min-h-screen place-items-center p-6"><div className="hud-panel max-w-lg p-8 text-center"><h1 className="font-display text-2xl font-bold">Attempt unavailable</h1><p className="mt-3 text-sm text-muted-foreground">The attempt could not be found or you do not have access to it.</p><Button onClick={() => setLocation("/dashboard")} className="mt-6 bg-cyan-300 text-slate-950 hover:bg-cyan-200">Return to dashboard</Button></div></div>;
  if (exam.status !== "in_progress") return <div className="grid min-h-screen place-items-center tech-label">Opening submission record…</div>;
  const question = data.questions[currentIndex];
  const currentAnswer = answers[question.id] ?? data.answers.find(answer => answer.questionId === question.id)?.selectedOption ?? null;
  const currentReview = review[question.id] ?? Boolean(data.answers.find(answer => answer.questionId === question.id)?.markedForReview);
  const answerQuestion = (choice: string) => { const next = currentAnswer === choice ? null : choice; setAnswers(values => ({ ...values, [question.id]: next })); saveAnswer.mutate({ attemptId, questionId: question.id, selectedOption: next as "A" | "B" | "C" | "D" | null, markedForReview: currentReview }, { onError: error => toast.error(error.message) }); };
  const toggleReview = () => { const next = !currentReview; setReview(values => ({ ...values, [question.id]: next })); saveAnswer.mutate({ attemptId, questionId: question.id, selectedOption: currentAnswer as "A" | "B" | "C" | "D" | null, markedForReview: next }); };
  const startSession = async () => { await proctoring.start(); try { if (!document.fullscreenElement) await document.documentElement.requestFullscreen(); } catch { toast.message("Fullscreen could not be enabled. This event may be recorded if your exam requires it."); } };
  return <div className="min-h-screen bg-[#05060b]"><header className="border-b border-cyan-200/15 bg-[#080916]/95"><div className="container flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="tech-label">Protected assessment</p><h1 className="font-display text-lg font-semibold">{exam.title}</h1></div><div className="flex items-center gap-3"><div className={`border px-3 py-2 font-display text-lg ${remainingSeconds !== null && remainingSeconds < 300 ? "border-pink-400/55 bg-pink-400/10 text-pink-200" : "border-cyan-300/35 bg-cyan-300/5 text-cyan-100"}`}><Clock3 className="mr-2 inline h-4 w-4" />{remainingSeconds === null ? "--:--" : asTime(remainingSeconds)}</div><Button disabled={submit.isPending} onClick={() => { if (window.confirm("Submit this exam now? You cannot change answers after submission.")) submit.mutate({ attemptId, reason: "manual" }); }} className="bg-pink-400 text-slate-950 hover:bg-pink-300"><Send className="mr-1 h-4 w-4" />Submit</Button></div></div></header>
  {warning && <div className="container pt-4"><div className="flex items-start gap-3 border border-pink-400/45 bg-pink-400/10 p-4 text-sm text-pink-100"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" /><div className="flex-1"><p className="font-semibold">Integrity notice</p><p className="mt-1 text-pink-100/80">{warning}</p></div><button onClick={() => setWarning(null)} className="text-xs text-pink-200">Dismiss</button></div></div>}
  <main className="container grid gap-5 py-5 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="hud-panel min-h-[570px] p-5 sm:p-8"><div className="flex items-center justify-between gap-4"><p className="tech-label">Question {currentIndex + 1} / {data.questions.length}</p><button onClick={toggleReview} className={`flex items-center gap-2 border px-3 py-1.5 text-xs ${currentReview ? "border-pink-400/50 bg-pink-400/10 text-pink-200" : "border-cyan-200/20 text-muted-foreground"}`}><Flag className="h-3.5 w-3.5" />{currentReview ? "Marked for review" : "Mark for review"}</button></div><div className="neon-line mt-5" /><h2 className="mt-8 max-w-3xl font-display text-xl font-semibold leading-8 sm:text-2xl">{question.prompt}</h2><div className="mt-8 grid gap-3">{(["A", "B", "C", "D"] as const).map(choice => { const content = question[`option${choice}`]; const selected = currentAnswer === choice; return <button key={choice} onClick={() => answerQuestion(choice)} className={`flex items-center gap-4 border p-4 text-left transition-colors ${selected ? "border-cyan-300 bg-cyan-300/10 text-cyan-50 shadow-[0_0_22px_rgba(34,211,238,.11)]" : "border-cyan-200/15 bg-black/10 hover:border-cyan-200/35"}`}><span className={`grid h-8 w-8 shrink-0 place-items-center border font-display text-sm ${selected ? "border-cyan-200 bg-cyan-300 text-slate-950" : "border-cyan-200/25 text-cyan-100"}`}>{selected ? <Check className="h-4 w-4" /> : choice}</span><span className="text-sm leading-6">{content}</span></button> })}</div><div className="mt-10 flex items-center justify-between"><Button variant="outline" disabled={currentIndex === 0} onClick={() => setCurrentIndex(index => index - 1)} className="border-cyan-200/25 bg-transparent text-cyan-100 hover:bg-cyan-300/10"><ChevronLeft className="mr-1 h-4 w-4" />Previous</Button><Button variant="outline" disabled={currentIndex === data.questions.length - 1} onClick={() => setCurrentIndex(index => index + 1)} className="border-cyan-200/25 bg-transparent text-cyan-100 hover:bg-cyan-300/10">Next<ChevronRight className="ml-1 h-4 w-4" /></Button></div></section>
  <aside className="space-y-5"><div className="hud-panel overflow-hidden"><div className="relative aspect-video bg-black"><video ref={proctoring.videoRef} muted playsInline className="h-full w-full object-cover" /><div className="absolute inset-0 border border-cyan-300/25" /><div className="absolute left-3 top-3 flex items-center gap-2 bg-black/55 px-2 py-1 tech-label text-[0.5rem]"><span className={`h-1.5 w-1.5 rounded-full ${proctoring.status === "monitoring" ? "bg-cyan-300 shadow-[0_0_10px_#22d3ee]" : "bg-slate-500"}`} />{proctoring.status === "monitoring" ? `Local signal · ${proctoring.faceCount ?? 0} face` : "Camera inactive"}</div></div><div className="p-4"><div className="flex items-start gap-3"><ScanFace className="mt-0.5 h-5 w-5 text-cyan-200" /><div><p className="text-sm font-medium">Device &amp; presence check</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Camera processing remains in this browser. Only configured integrity event metadata is sent for the attempt record.</p></div></div>{proctoring.error && <p className="mt-3 text-xs leading-5 text-pink-200">{proctoring.error}</p>}<Button onClick={startSession} disabled={proctoring.status === "requesting" || proctoring.status === "monitoring"} className="mt-4 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Camera className="mr-1 h-4 w-4" />{proctoring.status === "monitoring" ? "Device check active" : "Begin device check"}</Button><p className="mt-2 flex items-center gap-1.5 text-[0.65rem] text-muted-foreground"><Expand className="h-3.5 w-3.5" />Fullscreen is requested after you begin the check.</p><DeviceReadiness cameraStatus={proctoring.status} /></div></div><SupportChat attemptId={attemptId} />
  <div className="hud-panel p-4"><div className="flex items-center justify-between"><p className="tech-label">Question map</p><span className="text-xs text-muted-foreground">{Object.values({ ...Object.fromEntries(data.answers.map(answer => [answer.questionId, answer.selectedOption])), ...answers }).filter(Boolean).length}/{data.questions.length} answered</span></div><div className="mt-4 grid grid-cols-6 gap-2">{data.questions.map((item, index) => { const selected = answers[item.id] ?? data.answers.find(answer => answer.questionId === item.id)?.selectedOption; const flagged = review[item.id] ?? Boolean(data.answers.find(answer => answer.questionId === item.id)?.markedForReview); return <button key={item.id} onClick={() => setCurrentIndex(index)} className={`relative grid aspect-square place-items-center border text-xs ${index === currentIndex ? "border-pink-400 bg-pink-400/15 text-pink-100" : selected ? "border-cyan-300/40 bg-cyan-300/10 text-cyan-100" : "border-cyan-200/15 text-muted-foreground"}`}>{index + 1}{flagged && <span className="absolute right-1 top-1 h-1.5 w-1.5 bg-pink-400" />}</button> })}</div></div><div className="border border-cyan-200/15 bg-cyan-300/5 p-4 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mb-2 h-5 w-5 text-cyan-200" />Signals should be reviewed in context. Brief interruptions and detection errors are not treated as automatic misconduct decisions.</div></aside></main></div>;
}
