import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { MailCheck, UserPlus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

export default function StudentSignUp() {
  const [, setLocation] = useLocation();
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [collegeName, setCollegeName] = useState(""); const [rollNumber, setRollNumber] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState("");
  const signUp = trpc.proctorx.credentials.signUp.useMutation({ onError: error => toast.error(error.message) });
  const submit = () => { if (password !== confirm) { toast.error("Passwords do not match."); return; } signUp.mutate({ fullName, email, password, collegeName: collegeName || null, rollNumber: rollNumber || null, origin: window.location.origin }); };
  const inputStyle = "border-cyan-200/30 bg-black/25 placeholder:text-slate-400";
  if (signUp.data) return <div className="grid-backdrop grid min-h-screen place-items-center bg-[#05060b] p-5"><main className="hud-panel w-full max-w-xl p-7 text-center sm:p-9"><MailCheck className="mx-auto h-12 w-12 text-cyan-300" /><p className="mt-6 tech-label">Enrollment pending verification</p><h1 className="mt-2 font-display text-3xl font-bold">Check your email</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Your student account is created. Verify the email address before signing in.</p>{signUp.data.verificationDelivery.mode === "preview" && signUp.data.verificationDelivery.previewUrl ? <a href={signUp.data.verificationDelivery.previewUrl} className="mt-6 inline-flex w-full items-center justify-center bg-cyan-300 px-4 py-3 text-sm font-semibold text-slate-950">Open development verification link</a> : <p className="mt-6 border border-cyan-200/15 bg-cyan-300/5 p-4 text-xs leading-5 text-muted-foreground">If transactional email is configured, a verification message has been sent. If it is not configured in production, ask an administrator to configure an email sender.</p>}<Button onClick={() => setLocation("/signin")} variant="outline" className="mt-4 border-cyan-200/25 text-cyan-100">Return to sign in</Button></main></div>;
  return <div className="grid-backdrop grid min-h-screen place-items-center bg-[#05060b] p-5"><main className="hud-panel w-full max-w-xl p-7 sm:p-9"><button onClick={() => setLocation("/")} className="font-display font-bold">PROCTOR<span className="text-pink-400">X</span></button><p className="mt-8 tech-label">Candidate enrollment</p><h1 className="mt-2 font-display text-3xl font-bold">Create student account</h1><p className="mt-2 text-sm text-muted-foreground">Create your credentials and confirm your email address before accessing assessments.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Input value={fullName} onChange={event => setFullName(event.target.value)} placeholder="Full name" className={`${inputStyle} sm:col-span-2`} /><Input value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="Email address" className={`${inputStyle} sm:col-span-2`} /><Input value={collegeName} onChange={event => setCollegeName(event.target.value)} placeholder="College or institution (optional)" className={inputStyle} /><Input value={rollNumber} onChange={event => setRollNumber(event.target.value)} placeholder="Roll number (optional)" className={inputStyle} /><Input value={password} onChange={event => setPassword(event.target.value)} type="password" placeholder="Password (at least 10 characters)" className={inputStyle} /><Input value={confirm} onChange={event => setConfirm(event.target.value)} type="password" placeholder="Confirm password" className={inputStyle} /></div><Button disabled={signUp.isPending || !fullName || !email || password.length < 10 || !confirm} onClick={submit} className="mt-5 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200"><UserPlus className="mr-1 h-4 w-4" />{signUp.isPending ? "Creating account…" : "Create student account"}</Button><p className="mt-5 text-center text-sm text-muted-foreground">Already have an account? <Link href="/signin" className="text-pink-300 hover:text-pink-200">Sign in</Link></p></main></div>;
}
