import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { CalendarClock, ChevronRight, ClipboardCheck, FileText, UserRound } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

function formatDate(value: Date | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Available now"; }

export default function StudentDashboard() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const overview = trpc.proctorx.student.overview.useQuery(undefined, { enabled: Boolean(user) });
  const startAttempt = trpc.proctorx.student.startAttempt.useMutation({ onSuccess: result => setLocation(`/exam/${result.attemptId}`), onError: error => toast.error(error.message) });
  if (loading) return <div className="grid min-h-screen place-items-center tech-label">Opening candidate workspace…</div>;
  if (!user) return <div className="grid-backdrop grid min-h-screen place-items-center p-6"><div className="hud-panel max-w-md p-8 text-center"><UserRound className="mx-auto h-10 w-10 text-cyan-300" /><h1 className="mt-5 font-display text-3xl font-bold">Candidate access</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Sign in to access your exam schedule, attempts, and results.</p><Button onClick={() => startLogin()} className="neon-button mt-7 w-full bg-pink-400 text-slate-950 hover:bg-pink-300">Sign in securely</Button></div></div>;
  const data = overview.data;
  const completed = data?.attempts.filter(attempt => attempt.status !== "in_progress") ?? [];
  return <div className="min-h-screen bg-background"><header className="border-b border-cyan-200/10 bg-[#080916]/85 backdrop-blur"><div className="container flex items-center justify-between py-4"><button onClick={() => setLocation("/")} className="font-display font-bold">PROCTOR<span className="text-pink-400">X</span></button><div className="flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:inline">{user.name ?? "Candidate"}</span><Button size="sm" variant="outline" onClick={() => setLocation("/")} className="border-cyan-200/25 bg-transparent text-cyan-100">Exit workspace</Button></div></div></header><main className="container py-8 sm:py-12"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="tech-label">Candidate workspace / {user.role === "admin" ? "administrator preview" : "student"}</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Assessment dashboard</h1><p className="mt-2 text-sm text-muted-foreground">Your schedule, completed attempts, and result availability in one place.</p></div><div className="hud-panel p-3 text-right"><p className="tech-label text-[0.55rem]">Profile integrity</p><p className="mt-1 text-sm">{data?.profile?.rollNumber ? "Profile verified" : "Complete profile before your first attempt"}</p></div></div>
    <div className="mt-9 grid gap-4 sm:grid-cols-3"><Metric icon={CalendarClock} label="Available exams" value={String(data?.availableExams.length ?? 0)} /><Metric icon={ClipboardCheck} label="Completed attempts" value={String(completed.length)} /><Metric icon={FileText} label="Results released" value={String(completed.filter(attempt => attempt.releaseResultsImmediately).length)} /></div>
    <section className="mt-10 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><div className="hud-panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="tech-label">Exam queue</p><h2 className="mt-1 font-display text-xl font-semibold">Upcoming &amp; active exams</h2></div><CalendarClock className="h-5 w-5 text-cyan-300" /></div><div className="mt-6 divide-y divide-cyan-200/10">{overview.isLoading ? <p className="py-7 text-sm text-muted-foreground">Loading your assessment schedule…</p> : data?.availableExams.length ? data.availableExams.map(exam => <div key={exam.id} className="flex flex-col gap-4 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display font-semibold">{exam.title}</p><p className="mt-1 text-sm text-muted-foreground">{exam.description ?? "Timed multiple-choice assessment"}</p><p className="mt-2 tech-label text-[0.54rem]">{Math.round(exam.durationSeconds / 60)} minutes · {formatDate(exam.startsAt)}</p></div><Button disabled={startAttempt.isPending} onClick={() => startAttempt.mutate({ examId: exam.id })} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200">Begin check <ChevronRight className="ml-1 h-4 w-4" /></Button></div>) : <EmptyState label="No assessments are currently available." copy="When an administrator publishes an exam for your scheduled window, it will appear here." />}</div></div>
      <div className="hud-panel p-5 sm:p-7"><p className="tech-label">Candidate profile</p><h2 className="mt-1 font-display text-xl font-semibold">Identity record</h2><div className="mt-6 space-y-4 text-sm"><Detail label="Name" value={data?.profile?.fullName ?? user.name ?? "Not provided"} /><Detail label="Institution" value={data?.profile?.collegeName ?? "Not provided"} /><Detail label="Roll number" value={data?.profile?.rollNumber ?? "Not provided"} /></div><p className="mt-7 border-t border-cyan-200/10 pt-5 text-xs leading-5 text-muted-foreground">Profile details are used only to identify your assessment records. Add registration fields through the profile endpoint before formal deployment.</p></div></section>
    <section className="hud-panel mt-6 p-5 sm:p-7"><div><p className="tech-label">Attempt archive</p><h2 className="mt-1 font-display text-xl font-semibold">Completed &amp; in-progress attempts</h2></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-cyan-200/15 text-xs text-muted-foreground"><tr><th className="pb-3 font-medium">Exam</th><th className="pb-3 font-medium">Status</th><th className="pb-3 font-medium">Score</th><th className="pb-3 font-medium">Submission</th><th className="pb-3" /></tr></thead><tbody>{data?.attempts.length ? data.attempts.map(attempt => <tr key={attempt.id} className="border-b border-cyan-200/10"><td className="py-4 font-medium">{attempt.examTitle}</td><td className="py-4"><span className="border border-cyan-200/20 bg-cyan-300/5 px-2 py-1 text-xs text-cyan-100">{attempt.status.replace("_", " ")}</span></td><td className="py-4">{attempt.score === null ? "Pending" : `${attempt.score} / ${attempt.maxScore}`}</td><td className="py-4 text-muted-foreground">{attempt.submissionReason?.replace("_", " ") ?? "In progress"}</td><td className="py-4 text-right"><Button size="sm" variant="ghost" onClick={() => setLocation(attempt.status === "in_progress" ? `/exam/${attempt.id}` : `/result/${attempt.id}`)} className="text-pink-300 hover:text-pink-200">Open</Button></td></tr>) : <tr><td colSpan={5} className="py-8 text-center text-muted-foreground">No attempts have been recorded yet.</td></tr>}</tbody></table></div></section>
  </main></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof CalendarClock; label: string; value: string }) { return <div className="hud-panel p-5"><Icon className="h-5 w-5 text-pink-300" /><p className="mt-5 font-display text-3xl font-bold text-cyan-100">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="tech-label text-[0.53rem]">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function EmptyState({ label, copy }: { label: string; copy: string }) { return <div className="py-8"><p className="font-medium">{label}</p><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{copy}</p></div>; }
